// <auto-generated />
using System;
using ConferenceManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ConferenceManagement.Data.Migrations
{
    [DbContext(typeof(ConferenceDbContext))]
    [Migration("20190611060706_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ConferenceManagement.Data.Entities.Conference", b =>
                {
                    b.Property<int>("IdConference")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("IdConference");

                    b.ToTable("Conferences");
                });

            modelBuilder.Entity("ConferenceManagement.Data.Entities.Speaker", b =>
                {
                    b.Property<int>("IdSpeaker")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName");

                    b.Property<int>("IdConference");

                    b.Property<string>("LastName");

                    b.Property<DateTime>("SpeechDateTime");

                    b.Property<string>("SpeechName");

                    b.HasKey("IdSpeaker");

                    b.HasIndex("IdConference");

                    b.ToTable("Speakers");
                });

            modelBuilder.Entity("ConferenceManagement.Data.Entities.Speaker", b =>
                {
                    b.HasOne("ConferenceManagement.Data.Entities.Conference")
                        .WithMany("Speakers")
                        .HasForeignKey("IdConference")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
